/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#131e17",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#007166",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#aebbb0",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "surface-tint": "#2c6859",
        "tertiary-fixed-dim": "#bdcabe",
        "inverse-primary": "#95d3c0",
        "outline": "#707975",
        "on-secondary-fixed-variant": "#005048",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed": "#d9e6da",
        "tertiary-container": "#3f4b43",
        "secondary-fixed-dim": "#67d9c9",
        "tertiary": "#29352d",
        "surface-container-high": "#e6e8ea",
        "surface": "#f7f9fb",
        "on-primary-container": "#87c4b2",
        "primary-fixed": "#b1efdc",
        "primary-container": "#0f5244",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "on-background": "#191c1e",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#95d3c0",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#85f6e5",
        "on-secondary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#3e4a41",
        "on-primary-fixed": "#002019",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#0c5042",
        "secondary-container": "#85f6e5",
        "primary": "#003a2e",
        "on-surface-variant": "#404945",
        "outline-variant": "#bfc9c4",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "secondary": "#006a60"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "48px",
        "sm": "16px",
        "md": "24px",
        "container-max": "1440px",
        "sidebar-width": "260px",
        "base": "4px",
        "lg": "32px",
        "xs": "8px",
        "gutter": "20px"
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "data-display": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "display-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "data-display": ["28px", {"lineHeight": "34px", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-lg": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
